import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../lib/prisma';
import { asyncHandler } from '../lib/asyncHandler';
import { Errors } from '../lib/apiError';
import { generateTempPassword, hashPassword } from '../lib/auth';
import { toEmployee } from '../lib/mappers';
import { requireRole } from '../middleware/auth';

export const employeesRouter = Router();

employeesRouter.get(
  '/manager/employees',
  requireRole('MANAGER'),
  asyncHandler(async (_req, res) => {
    const employees = await prisma.user.findMany({ where: { role: 'EMPLOYEE' }, orderBy: { createdAt: 'desc' } });
    res.json(employees.map(toEmployee));
  }),
);

const createEmployeeSchema = z.object({
  name: z.string().min(1, 'Ten khong duoc de trong.'),
  email: z.string().email('Email khong hop le.'),
  phone: z.string().optional(),
  password: z.string().min(6).optional(),
});

employeesRouter.post(
  '/manager/employees',
  requireRole('MANAGER'),
  asyncHandler(async (req, res) => {
    const body = createEmployeeSchema.parse(req.body);
    const existing = await prisma.user.findUnique({ where: { email: body.email } });
    if (existing) throw Errors.conflict('EMAIL_EXISTS', 'Email nay da duoc su dung.');

    const autoGenerated = !body.password;
    const plainPassword = body.password ?? generateTempPassword();

    const employee = await prisma.user.create({
      data: {
        name: body.name,
        email: body.email,
        phone: body.phone,
        passwordHash: await hashPassword(plainPassword),
        role: 'EMPLOYEE',
      },
    });

    res.status(201).json({ ...toEmployee(employee), temporaryPassword: autoGenerated ? plainPassword : null });
  }),
);

const patchSchema = z.object({ active: z.boolean() });

employeesRouter.patch(
  '/manager/employees/:id',
  requireRole('MANAGER'),
  asyncHandler(async (req, res) => {
    const body = patchSchema.parse(req.body);
    const id = Number(req.params.id);
    const employee = await prisma.user.findFirst({ where: { id, role: 'EMPLOYEE' } });
    if (!employee) throw Errors.notFound('Khong tim thay nhan vien.');
    const updated = await prisma.user.update({ where: { id }, data: { active: body.active } });
    res.json(toEmployee(updated));
  }),
);
